### ISSUE TITLE
Signing Up routing 

### ISSUE THREAD

**Issue by developernick** [WDI-Woodstock-Sally/Trivia-App#2]
As a user you can Sign-Up for an account by creating a username and password. 

Expected: User signs-up and is routed to profile page where you can join game or log-out

Issue: After user submits, you are routed to "/users". 

Solution: Route users to "/profile"

**Comment by code-for-coffee** [comment]
Looks like you fixed this in the SessionController with `redirect_to "/profile"` on line 7! Nice. Feel free to **close** this issue.
